name: release
on:
  push:
    tags:
      - 'v*'          # e.g. v0.1.0

permissions:
  contents: write
  id-token: write     # for provenance
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm test --if-present

      # Optional: ensure README & types are included in the tarball
      - run: npm pack --dry-run

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  github-release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Build release tarball
        run: echo "pkg=$(npm pack)" >> $GITHUB_OUTPUT
        id: pack
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: ${{ steps.pack.outputs.pkg }}
